CREATE DATABASE IF NOT EXISTS ops;

USE ops;

CREATE TABLE IF NOT EXISTS orders_ops (
  order_id BINARY(16) PRIMARY KEY,
  partner_id VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  total_amount DECIMAL(12, 2) NOT NULL DEFAULT 0,
  currency VARCHAR(8) NOT NULL DEFAULT 'USD',
  created_ts DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_ts DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  is_deleted BOOLEAN NOT NULL DEFAULT 0,
  KEY idx_orders_partner (partner_id)
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;